#!/data/data/com.termux/files/usr/bin/bash
rm -r $HOME/.gqe-data-v0.2 >/dev/null 2>&1
mkdir -p $HOME/.gqe-data-v0.2
pkill -f termux-x11
termux-x11 :13 & >/dev/null 2>&1
env WINEDLLOVERRIDES="mscoree=" WINEPREFIX=$HOME/.gqe-data-v0.2 WINEARCH=win64 DISPLAY=:13 grun /data/data/com.termux/files/usr/glibc/bin/box64 /data/data/com.termux/files/usr/glibc/bin/wine /data/data/com.termux/files/usr/glibc/bin/wineboot -u >/dev/null 2>&1
pkill termux-x11

echo -e "Configuring Wine...\n"
rm -rf /data/data/com.termux/files/usr/opt/{InputBridge,startmenu} startmenulink.tar.xz startmenu-v0.2.tar.xz
wget --quiet --show-progress -P $HOME/.gqe-data-v0.2/drive_c/windows https://github.com/radzikpwnz/tfm/releases/download/v1.0.1/TFM.exe
wget --quiet --show-progress https://github.com/ocnedkf/GQE-emulator/releases/download/v0.2-beta/startmenulink.tar.xz
wget --quiet --show-progress https://github.com/ocnedkf/GQE-emulator/releases/download/v0.2-beta/startmenu-v0.2.tar.xz
tar -xJf startmenu-v0.2.tar.xz -C /data/data/com.termux/files/usr/opt
tar -xJf startmenulink.tar.xz -C "$HOME/.gqe-data-v0.2/drive_c/users/steamuser/AppData/Roaming/Microsoft/Windows/Start Menu" >/dev/null 2>&1
rm -f startmenulink.tar.xz startmenu-v0.2.tar.xz

echo -e "Downloading InputBridge...\n"
rm -f inputbridge.tar.xz
wget --quiet --show-progress https://github.com/ocnedkf/GQE-emulator/releases/download/v0.1-beta/inputbridge.tar.xz
tar -xJf inputbridge.tar.xz -C /data/data/com.termux/files/usr/opt
rm -f inputbridge.tar.xz

echo ""
echo -e "Installing InputBridge...\n"
touch install-ib.bat
echo "cd Z:\\usr\\opt\\InputBridge\\" > install-ib.bat
echo ".\install.bat" >> install-ib.bat
echo "exit" >> install-ib.bat
env WINEPREFIX=$HOME/.gqe-data-v0.2 grun /data/data/com.termux/files/usr/glibc/bin/box64 /data/data/com.termux/files/usr/glibc/bin/wine cmd /c Z:\\home\\install-ib.bat >/dev/null 2>&1
rm install-ib.bat

echo -e "Downloading DLL file...\n"
wget --quiet --show-progress -P $HOME/.gqe-data/drive_c/windows/syswow64 https://github.com/ocnedkf/GQE-emulator/releases/download/v0.1-beta/mfc42.dll

echo ""
echo -e "Setting DLL overrides...\n"
rm -f dllsetting.reg
wget --quiet --show-progress https://github.com/ocnedkf/GQE-emulator/releases/download/v0.2-beta/dllsetting.reg
env WINEPREFIX=$HOME/.gqe-data-v0.2 grun /data/data/com.termux/files/usr/glibc/bin/box64 /data/data/com.termux/files/usr/glibc/bin/wine /data/data/com.termux/files/usr/glibc/bin/regedit "$(realpath dllsetting.reg)" >/dev/null 2>&1 
rm -f dllsetting.reg

echo ""
echo -e "Initializing visual environment...\n"
rm -f wallpaper.bmp
wget --quiet -P $HOME/.gqe-data/drive_c https://github.com/ocnedkf/GQE-emulator/releases/download/v0.2-beta/wallpaper.bmp
wget --quiet https://github.com/ocnedkf/GQE-emulator/releases/download/v0.2-beta/wallpapersetting.reg
env WINEPREFIX=$HOME/.gqe-data-v0.2 grun /data/data/com.termux/files/usr/glibc/bin/box64 /data/data/com.termux/files/usr/glibc/bin/wine /data/data/com.termux/files/usr/glibc/bin/regedit "$(realpath wallpapersetting.reg)" >/dev/null 2>&1

echo -e "Configuring startup scripts...\n"
rm -rf $HOME/storage/shared/.gqe-start
mkdir -p $HOME/storage/shared/.gqe-start
touch $HOME/storage/shared/.gqe-start/start-gqe-v0.2.bat
echo 'start /min Z:\\usr\\opt\\InputBridge\\ib.exe' > $HOME/storage/shared/.gqe-start/start-gqe-v0.2.bat
echo 'start TFM.exe C:\' >> $HOME/storage/shared/.gqe-start/start-gqe-v0.2.bat

touch $HOME/storage/shared/.gqe-start/mesa_var.txt
touch $HOME/storage/shared/.gqe-start/mesa_var_v.txt
touch $HOME/storage/shared/.gqe-start/mesa_var_f.txt

echo -e "Configuration Completed\n"
