#!/data/data/com.termux/files/usr/bin/bash

export HOME="/data/data/com.termux/files/home"
export GQE_DATA="$HOME/.gqe-data-v0.3"
export WINEPREFIX="$GQE_DATA/.wine"
export WINEARCH=win64
export BOX64_PATH="$GQE_DATA/wine/bin"
export BOX64_LD_LIBRARY_PATH="$GQE_DATA/wine/lib:$GQE_DATA/lib:$GQE_DATA/box64/lib/box64-x86_64-linux-gnu"
export PREFIX="/data/data/com.termux/files/usr"
export BOX64="$GQE_DATA/box64/bin/box64"

download_file() {
    url="$1"
    hash_value="$2"
    file_name="$3"
    echo_file_name="$4"
    echo ""
    echo -e "Downloading $echo_file_name...\n"
    rm -f "$PREFIX/tmp/$file_name"

    if ! wget --quiet --show-progress -O "$PREFIX/tmp/$file_name" "$url"; then
    echo ""
    echo -e "\033[31mERROR: Failed to download $echo_file_name, check network!\033[0m\n"
    exit 1
    fi

    sha256sum --status -c <<< "$hash_value  $PREFIX/tmp/$file_name"
    if [ $? -ne 0 ]; then
    echo ""
    echo -e "\033[31mERROR: Hash verification failed for $file_name. Please check the file integrity.\033[0m\n"
    rm -f "$PREFIX/tmp/$file_name"
    exit 1
    fi
}

extract_file() {
    echo_file_name="$1"
    file_name="$2"
    dest_dir="$3"
    echo ""
    echo -e "Unpacking $echo_file_name...\n"
    mkdir -p "$dest_dir"
    if tar -xvJf $PREFIX/tmp/$file_name -C "$dest_dir" >/dev/null 2>&1; then
    rm -f "$PREFIX/tmp/$file_name"
    else
    echo ""
    echo -e "\033[31mERROR: Failed to unpack $file_name. Please try again.\033[0m\n"
    exit 1
    fi
}

rm -rf $WINEPREFIX
pkill -f termux-x11
termux-x11 :13 >/dev/null 2>&1 &
env WINEDLLOVERRIDES="mscoree=" DISPLAY=:13 grun $BOX64 wine wineboot -i >/dev/null 2>&1
pkill termux-x11

echo -e "Configuring Wine...\n"
download_file https://github.com/radzikpwnz/tfm/releases/download/v1.0.1/TFM.exe "e0b4688675a1d09dd3ce1517fe88e5f506cb1eceadfaadd94dc2cb4b9c69c30a" "tfm.exe" "TFM"
mv $PREFIX/tmp/tfm.exe $WINEPREFIX/drive_c/windows/tfm.exe
download_file https://github.com/ocnedkf/GQE-emulator/releases/download/v0.3-beta/startmenulink.tar.xz "0553f26bbba9ab0102daa58beff81af080b8e221eb8e5ff3354d5e3028dc9952" "startmenulink.tar.xz" "Start Menu Link"
extract_file "Start Menu Link" "startmenulink.tar.xz" "$WINEPREFIX/drive_c/users/steamuser/AppData/Roaming/Microsoft/Windows/Start Menu"
download_file https://github.com/ocnedkf/GQE-emulator/releases/download/v0.3-beta/startmenu-v0.3.tar.xz "761fd6a5e3cd30a0522814c80150effccd26803c44a79a9bb22aea748859dde3" "startmenu-v0.3.tar.xz" "Start Menu"
extract_file "Start Menu Files" "startmenu-v0.3.tar.xz" "$GQE_DATA/STARTMENU"

# download and extract InputBridge
rm -rf $HOME/.gqe-data-v0.3/InputBridge
download_file https://github.com/ocnedkf/GQE-emulator/releases/download/v0.1-beta/inputbridge.tar.xz "93c9da74b8c9cde3e595033e73bd49f0451cb9d5621aab76a652e0aecf1819af" "inputbridge.tar.xz" "InputBridge"
extract_file "InputBridge" "inputbridge.tar.xz" "$GQE_DATA"

echo ""
echo -e "Installing InputBridge...\n"
touch install-ib.bat
echo "cd Z:\\home\\.gqe-data-v0.3\\InputBridge\\" > install-ib.bat
echo ".\install.bat" >> install-ib.bat
echo "exit" >> install-ib.bat
grun $BOX64 wine cmd /c Z:\\home\\install-ib.bat >/dev/null 2>&1
rm install-ib.bat

# download mfc42 dll file
download_file https://github.com/ocnedkf/GQE-emulator/releases/download/v0.1-beta/mfc42.dll "40e83003f7d136276cd76fde17639f8cec04c3bc85d108446fa511aab1df0506" "mfc42.dll" "DLL File"
mv $PREFIX/tmp/mfc42.dll $WINEPREFIX/drive_c/windows/syswow64/mfc42.dll

echo ""
echo -e "Setting DLL overrides...\n"
download_file https://github.com/ocnedkf/GQE-emulator/releases/download/v0.1-beta/dllsetting.reg "13f6ca809b555d29e242ece34e65aaaa00fb04b0ab7619d6bfc028a8c66ddd1a" "dllsetting.reg" "DLL Setting REG File"
mv $PREFIX/tmp/dllsetting.reg .
grun $BOX64 wine regedit "$(realpath dllsetting.reg)" >/dev/null 2>&1 
rm -f dllsetting.reg

echo ""
echo -e "Configuring startup scripts...\n"
rm -rf $HOME/storage/shared/.gqe-start
mkdir -p $HOME/storage/shared/.gqe-start
touch $HOME/storage/shared/.gqe-start/start-gqe-v0.3.bat
echo 'start /min Z:\\home\\.gqe-data-v0.3\\InputBridge\\ib.exe' > $HOME/storage/shared/.gqe-start/start-gqe-v0.3.bat
echo 'start tfm.exe C:\' >> $HOME/storage/shared/.gqe-start/start-gqe-v0.3.bat

echo ""
echo -e "Initializing visual environment...\n"
download_file https://github.com/ocnedkf/GQE-emulator/releases/download/v0.3-beta/wallpaper.bmp "d53a15d588b5bbe6a68d737c4a3d9ca93bf7dd6b75a7d4b5c9998ecdb12baa15" "wallpaper.bmp" "Wallpaper"
mv $PREFIX/tmp/wallpaper.bmp $WINEPREFIX/drive_c/wallpaper.bmp
download_file https://github.com/ocnedkf/GQE-emulator/releases/download/v0.3-beta/wallpapersetting.reg "1b7e003f5a3f2ee82241ff2ae841cbedadd53eb5186edf374d4239297bd7261f" "wallpapersetting.reg" "Wallpaper Setting REG File"
mv $PREFIX/tmp/wallpapersetting.reg .
touch set.bat
echo "regedit /s Z:\\home\\wallpapersetting.reg" > set.bat
grun $BOX64 wine Z://home//set.bat >/dev/null 2>&1
rm -f wallpapersetting.reg set.bat

echo -e "Creating configuration files...\n"
touch $HOME/storage/shared/.gqe-start/log.txt
touch $HOME/storage/shared/.gqe-start/mesa_var.txt
touch $HOME/storage/shared/.gqe-start/mesa_var_v.txt
touch $HOME/storage/shared/.gqe-start/mesa_var_f.txt
touch $HOME/storage/shared/.gqe-start/dxvk_settings.ini
touch $HOME/storage/shared/.gqe-start/all_var.txt

var_all(){
cat << 'EOF'
# GQE-emulator environment variables
export HOME=/data/data/com.termux/files/home
export GQE_DATA=$HOME/.gqe-data-v0.3
export DXVK_CONFIG_FILE="$HOME/storage/shared/.gqe-start/dxvk_settings.ini"
export PULSE_LATENCY_MSEC=20
export WINEPREFIX="$HOME/.gqe-data-v0.3/.wine"
export DXVK_ASYNC=1
export BOX64_ASYNC=1
export MESA_VK_DEVICE_SELECT="$(cat "$HOME/storage/shared/.gqe-start/mesa_var_v.txt")"
export VK_ICD_FILENAMES="$(cat "$HOME/storage/shared/.gqe-start/mesa_var_f.txt")"
export GALLIUM_DRIVER="$(cat "$HOME/storage/shared/.gqe-start/mesa_var.txt")"
export LOCPATH="$HOME/.gqe-data-v0.3/locale"
export PULSE_SERVER=127.0.0.1
export MESA_NO_ERROR=1
export DISPLAY=:13
export MESA_DEBUG=1
export BOX64_PATH=$HOME/.gqe-data-v0.3/wine/bin
export BOX64_LD_LIBRARY_PATH="$HOME/.gqe-data-v0.3/wine/lib:$HOME/.gqe-data-v0.3/lib:$GQE_DATA/box64/lib/box64-x86_64-linux-gnu"
export PREFIX=/data/data/com.termux/files/usr
export BOX64=$GQE_DATA/box64/bin/box64
export GALLIUM_HUD=simple,fps
EOF
}

var_all > $HOME/storage/shared/.gqe-start/all_var.txt
echo "dxvk.hud = 1" > $HOME/storage/shared/.gqe-start/dxvk_settings.ini
echo "virpipe" > $HOME/storage/shared/.gqe-start/mesa_var.txt

echo -e "Configuration Completed\n"
echo -e "Initialization completed\n"
rm -rf "$0"
