#!/data/data/com.termux/files/usr/bin/bash
echo -e "Welcome to the GQE installation script\n"
echo -e "We will now begin the installation process\n"
sleep 1
echo -e "Please grant storage permissions\n"
echo -e "If already granted, this can be ignored\n"
termux-setup-storage & sleep 0
sleep 4
if [ -e storage ]; then
echo -e "Failed to check the directory , Please ensure that you have granted storage permissions\n"
echo -e "Updating termux package\n"
apt-get clean
apt-get update >/dev/null 2>&1
apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade >/dev/null 2>&1
echo -e "Installing necessary\n"
pkg install x11-repo glibc-repo -y &>/dev/null
pkg install pulseaudio termux-x11 glibc-runner freetype-glibc libpulse-glibc libx11-glibc libxcb-glibc libxext-glibc libxft-glibc libxi-glibc libxrandr-glibc -y &>/dev/null
wget 
