#!/data/data/com.termux/files/usr/bin/bash
if [ ! -d "$HOME/.gqe-data-v0.2/drive_c" ]; then
clear
echo -e "Wine prefix missing! try reinitializing...\n"
rm -f initialization-sh
wget --show-progress --quiet https://raw.githubusercontent.com/ocnedkf/GQE-emulator/refs/heads/v0.2-beta/initialization-sh
chmod +x initialization-sh
./initialization-sh
rm -f initialization-sh
fi

if [ ! -d "$HOME/storage" ]; then
echo -e "External storage not found! Please check your storage permissions"
exit 1
fi

rm -rf $PREFIX/tmp/pulse-*
pulseaudio -k >/dev/null 2>&1
pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 >/dev/null 2>&1

pkill -f virgl
virgl_test_server --use-gles --use-egl-surfaceless &

pkill -f termux-x11
termux-x11 :13 & >/dev/null 2>&1

am start -n com.termux.x11/.MainActivity

env DXVK_ASYNC=1 BOX64_ASYNC=1 MESA_VK_DEVICE_SELECT=$(cat /data/data/com.termux/files/home/storage/shared/.gqe-start/mesa_var_v.txt) VK_ICD_FILENAMES=$(cat /data/data/com.termux/files/home/storage/shared/.gqe-start/mesa_var_f.txt) GALLIUM_DRIVER=$(cat /data/data/com.termux/files/home/storage/shared/.gqe-start/mesa_var.txt) WINEPREFIX=$HOME/.gqe-data-v0.2 LOCPATH=$HOME/.locale PULSE_SERVER=127.0.0.1 DXVK_HUD=1 MESA_NO_ERROR=1 DISPLAY=:13 grun /data/data/com.termux/files/usr/glibc/bin/box64 /data/data/com.termux/files/usr/glibc/bin/wine explorer /desktop=shell,1024x768 Z:\\home\\storage\\shared\\.gqe-start\\start-gqe-v0.2.bat >/dev/null 2>&1

pkill -f termux-x11
pulseaudio -k >/dev/null 2>&1
rm -rf $PREFIX/tmp/pulse-*
pkill -f virgl
