#!/data/data/com.termux/files/usr/bin/bash

if [ "$(uname -m)" != "aarch64" ]; then
echo "GQE-模拟器仅支持ARM64架构"
echo "请检查你的设备与Termux是否符合要求"
exit 1
fi

export HOME="/data/data/com.termux/files/home"

FREE_KB=$(df "$HOME" | awk 'NR==2 {print $4}')
if [ "$FREE_KB" -lt 5767168 ]; then
echo "存储空间不足，至少需要 5.5GB 可用空间"
exit 1
fi

export PREFIX="/data/data/com.termux/files/usr"

download_file() {
    url="$1"
    hash_value="$2"
    file_name="$3"
    echo_file_name="$4"
    echo ""
    echo -e "正在下载 $echo_file_name...\n"
    rm -f "$PREFIX/tmp/$file_name"

    if ! wget --quiet --show-progress -O "$PREFIX/tmp/$file_name" "$url"; then
    echo ""
    echo -e "\033[31m错误: 无法下载 $echo_file_name, 检查网络!\033[0m\n"
    exit 1
    fi

    sha256sum --status -c <<< "$hash_value  $PREFIX/tmp/$file_name"
    if [ $? -ne 0 ]; then
    echo ""
    echo -e "\033[31m错误: 检验 $file_name 哈希值失败, 请检查文件完整性\033[0m\n"
    rm -f "$PREFIX/tmp/$file_name"
    exit 1
    fi
}

extract_file() {
    echo_file_name="$1"
    file_name="$2"
    dest_dir="$3"
    echo ""
    echo -e "正在解压 $echo_file_name...\n"
    mkdir -p "$dest_dir"
    if tar -xJf $PREFIX/tmp/$file_name -C "$dest_dir" >/dev/null 2>&1; then
    rm -f "$PREFIX/tmp/$file_name"
    else
    echo ""
    echo -e "\033[31m错误: 解压 $file_name 失败, 请再试一次\033[0m\n"
    exit 1
    fi
}

clear

echo -e "欢迎使用GQE安装脚本\n"
echo -e "现在开始进行安装\n"
sleep 1

echo -e "请授予存储权限\n"
echo -e "若已授权可忽略\n"
termux-setup-storage & sleep 0
sleep 10
if [ ! -e $HOME/storage ]; then
echo -e "找不到目录，确认你是否已授权\n"
exit 1
fi

echo -e "更新Termux包...\n"
apt-get clean
apt-get update >/dev/null 2>&1
apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade >/dev/null 2>&1

echo -e "安装依赖项...\n"
pkg install x11-repo glibc-repo -y &>/dev/null
pkg install virglrenderer pulseaudio termux-x11-nightly glibc-runner alsa-lib-glibc freetype-glibc libpulse-glibc libx11-glibc libxcb-glibc libxext-glibc libxft-glibc libdrm-glibc libffi-glibc libicu-glibc libpciaccess-glibc libxml2-glibc libxshmfence-glibc libxi-glibc libxrandr-glibc vulkan-icd-loader-glibc tar xz-utils wget libepoxy-glibc libxkbcommon-glibc libxcursor-glibc libxcomposite-glibc libxinerama-glibc libmount-glibc libthai-glibc libgraphite-glibc libpixman-glibc libjpeg-turbo-glibc -y &>/dev/null

export GQE_DATA="$HOME/.gqe-data-v0.3"
export WINEPREFIX="$GQE_DATA/.wine"
export WINEARCH=win64
export BOX64_PATH="$GQE_DATA/wine/bin:$GQE_DATA/box64/bin:$PREFIX/glibc/bin"
export BOX64_LD_LIBRARY_PATH="$GQE_DATA/wine/lib:$GQE_DATA/lib:$GQE_DATA/box64/lib/box64-x86_64-linux-gnu"
export BOX64="$GQE_DATA/box64/bin/box64"

cd $HOME

# download and extract necessary files
download_file https://v6.gh-proxy.org/https://github.com/ocnedkf/GQE-emulator/releases/download/v0.2-beta/lib.tar.xz "bbc45aee29be45e8f90672e4cfac4f3d22baff20ca05131b44b38c5733dcd9e2" "lib.tar.xz" "额外依赖项"
extract_file "额外依赖项" "lib.tar.xz" "$GQE_DATA/lib"

echo -e "正在修复软链接..."
download_file https://v6.gh-proxy.org/https://raw.githubusercontent.com/ocnedkf/GQE-emulator/refs/heads/v0.3-beta/repair-symlinks.sh "ad15d49a2291db116d5029d9ecea611e58c74f0e119157b6fc70c5f17ea79479" "repair-symlinks.sh" "修复脚本"
mv $PREFIX/tmp/repair-symlinks.sh .
chmod +x repair-symlinks.sh
./repair-symlinks.sh

# download and extract box64
download_file https://v6.gh-proxy.org/https://github.com/ocnedkf/GQE-emulator/releases/download/v0.2-beta/box64.tar.xz "6ff2d48380f5a76e2f03c4023e71e1a1d4e5b84ca1948e59cb6f8b76fdd165a9" "box64.tar.xz" "Box64"
extract_file "Box64" box64.tar.xz "$GQE_DATA/box64"

echo ""
while true; do

echo "选择Wine版本... (输入数字并回车)"
echo ""
echo -e "1) Wine-9.16-custom(旧版)\n"
echo -e "2) Proton-Wine-11.0(实验性)\n"

read gqe

if [ "$gqe" = "1" ]; then

# download and extract wine
download_file https://v6.gh-proxy.org/https://github.com/ocnedkf/GQE-emulator/releases/download/v0.1-beta/winewow64.tar.xz "88d1d73569e869ccdb51e1c25f5d70963a23344ea9be188e5442995d70492484" "winewow64.tar.xz" "Wine"
extract_file "Wine" "winewow64.tar.xz" "$GQE_DATA/wine"

clear
echo -e "正在初始化 Wine...\n"
download_file https://v6.gh-proxy.org/https://raw.githubusercontent.com/ocnedkf/GQE-emulator/refs/heads/v0.3-beta/zh_CN/initialization-v0.1-sh "96066dd05102771a05b4dc1c2ea234fb9de5c8f79b6043d2144f519a73a0c207" "initialization-v0.1-sh" "初始化脚本"
mv $PREFIX/tmp/initialization-v0.1-sh .
chmod +x initialization-v0.1-sh
./initialization-v0.1-sh

# download and set up GQE startup script
download_file https://v6.gh-proxy.org/https://raw.githubusercontent.com/ocnedkf/GQE-emulator/refs/heads/v0.3-beta/zh_CN/start-gqe-old "cae42808b722f05e5cabb764b7e0e45e4d4e9e4f4512929f22b555a5405d9bf3" "start-gqe" "启动脚本"
mv $PREFIX/tmp/start-gqe $PREFIX/bin/start-gqe
chmod +x $PREFIX/bin/start-gqe

break

elif [ "$gqe" = "2" ]; then

# download and extract proton-wine
download_file https://v6.gh-proxy.org/https://github.com/ocnedkf/GQE-emulator/releases/download/v0.2-beta/proton-wine-11.0-wow64.tar.xz "a937c76416c261bcbdbd9b5b6c3dd8142fdaed7060b171e2cb65bc4188d4a1ef" "proton-wine-11.0-wow64.tar.xz" "Proton-Wine"
extract_file "Proton-Wine" "proton-wine-11.0-wow64.tar.xz" "$GQE_DATA/wine"

clear
echo -e "正在初始化 Wine...\n"
download_file https://v6.gh-proxy.org/https://raw.githubusercontent.com/ocnedkf/GQE-emulator/refs/heads/v0.3-beta/zh_CN/initialization-sh "2959e04cd455bf10aeaeb455ac48402207254c6a0d7f192c6341d515fa54bc44" "initialization-sh" "初始化脚本"
mv $PREFIX/tmp/initialization-sh .
chmod +x initialization-sh
./initialization-sh

# download and set up GQE startup script
download_file https://v6.gh-proxy.org/https://raw.githubusercontent.com/ocnedkf/GQE-emulator/refs/heads/v0.3-beta/zh_CN/start-gqe "22310910a0158daadda75896c801585e2c54f974fa7483cc49e270c96f9474af" "start-gqe" "启动脚本"
mv $PREFIX/tmp/start-gqe $PREFIX/bin/start-gqe
chmod +x $PREFIX/bin/start-gqe
break

else

clear
echo "输入错误，重新选择..."

fi
done

echo ""
echo -e "正在配置区文件...\n"
rm -rf "$GQE_DATA/locale"
mkdir -p "$GQE_DATA/locale"
grun $PREFIX/glibc/bin/localedef -f UTF-8 -c -i en_US "$GQE_DATA/locale/en_US.UTF-8"
grun $PREFIX/glibc/bin/localedef -f UTF-8 -c -i ja_JP "$GQE_DATA/locale/ja_JP.UTF-8"
grun $PREFIX/glibc/bin/localedef -f UTF-8 -c -i zh_CN "$GQE_DATA/locale/zh_CN.UTF-8"
grun $PREFIX/glibc/bin/localedef -f UTF-8 -c -i zh_TW "$GQE_DATA/locale/zh_TW.UTF-8"
grun $PREFIX/glibc/bin/localedef -f UTF-8 -c -i C "$GQE_DATA/locale/C.UTF-8"
grun $PREFIX/glibc/bin/localedef -f UTF-8 -c -i de_DE "$GQE_DATA/locale/de_DE.UTF-8"
grun $PREFIX/glibc/bin/localedef -f UTF-8 -c -i ko_KR "$GQE_DATA/locale/ko_KR.UTF-8"
grun $PREFIX/glibc/bin/localedef -f UTF-8 -c -i ru_RU "$GQE_DATA/locale/ru_RU.UTF-8"

# download and extract fonts
download_file https://v6.gh-proxy.org/https://github.com/ocnedkf/GQE-emulator/releases/download/v0.1-beta/fonts.tar.xz "c51a887f91f3b64cc218d417bdcaef84c93061c4451df79cff4ce9f631413254" "fonts.tar.xz" "字体文件"
extract_file "Fonts" "fonts.tar.xz" "$PREFIX/glibc/share/fonts"

# download and set up GQE termination script
download_file https://v6.gh-proxy.org/https://raw.githubusercontent.com/ocnedkf/GQE-emulator/refs/heads/v0.3-beta/zh_CN/kill-gqe "a6547afc5bf85527cb7646ba83d108b58064d565754c333ee74e60e07a87afcc" "kill-gqe" "终止文件"
mv $PREFIX/tmp/kill-gqe $PREFIX/bin/kill-gqe
chmod +x $PREFIX/bin/kill-gqe

echo ""
echo '开始运行GQE, 下次执行"start-gqe"以启动'
sleep 2

start-gqe

clear
rm -f "$0"
