#!/data/data/com.termux/files/usr/bin/bash

if [ ! -d "$HOME/.gqe-data/drive_c" ]; then
clear
echo -e "Wine前缀损坏！尝试重新初始化...\n"
rm -f initialization-zh-sh
wget --show-progress --quiet https://gh-proxy.org/https://raw.githubusercontent.com/ocnedkf/GQE-emulator/refs/heads/main/zh_CN/initialization-zh-sh
chmod +x initialization-zh-sh
./initialization-zh-sh
rm -f initialization-sh
fi

if [ ! -d "$HOME/storage" ]; then
echo -e "找不到外部存储！检查你的存储权限"
exit 1
fi

pkill -f virgl
virgl_test_server --use-gles --use-egl-surfaceless &

rm -rf $PREFIX/tmp/pulse-*
pulseaudio -k >/dev/null 2>&1
pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 >/dev/null 2>&1

pkill -f termux-x11
termux-x11 :13 & >/dev/null 2>&1

am start -n com.termux.x11/.MainActivity

env DXVK_ASYNC=1 BOX64_ASYNC=1 GALLIUM_DRIVER=$(cat /data/data/com.termux/files/home/storage/shared/.gqe-start/mesa_var.txt) WINEPREFIX=$HOME/.gqe-data LOCPATH=$HOME/.locale PULSE_SERVER=127.0.0.1 DXVK_HUD=1 MESA_NO_ERROR=1 LC_ALL=zh_CN.UTF-8 DISPLAY=:13 grun /data/data/com.termux/files/usr/glibc/bin/box64 /data/data/com.termux/files/usr/glibc/bin/wine64 explorer /desktop=shell,1024x768 Z:\\home\\storage\\shared\\.gqe-start\\start-gqe.bat >/dev/null 2>&1

pkill -f termux-x11
pkill -f virgl
pulseaudio -k >/dev/null 2>&1
rm -rf $PREFIX/tmp/pulse-*
