#!/data/data/com.termux/files/usr/bin/bash

show_info() {
cat << EOF
==================== 介绍 ====================

GQE-emulator by ocnedkf

GQE-emulator 是一个可用于运行windows x86_64程序的模拟器

详情请见 : https://github.com/ocnedkf/GQE-emulator/tree/v0.2-beta
EOF
}

show_help() {
cat << EOF
==================== 使用说明 ====================

usage : start-gqe [参数]
        start-gqe 正常启动GQE
        start-gqe --help/-h 打印帮助信息与介绍并退出
EOF
}

for cs in "$@"
do
    if [ "$cs" = "-h" ] || [ "$cs" = "--help" ]; then
        show_info
        show_help
        exit 0
    fi
done

if [ $# -gt 0 ]; then
    echo -e "不支持的参数\n"
    show_help
    exit 1
fi

if [ ! -d "$HOME/.gqe-data-v0.2/drive_c" ]; then
clear
echo -e "Wine前缀损坏！尝试重新初始化...\n"

if [ -f "/data/data/com.termux/files/usr/bin/wine64" ]; then
rm -f initialization-v0.1-sh
wget --show-progress --quiet https://gh-proxy.org/https://raw.githubusercontent.com/ocnedkf/GQE-emulator/refs/heads/v0.2-beta/initialization-v0.1-sh
chmod +x initialization-v0.1-sh
./initialization-v0.1-sh
rm -f initialization-v0.1-sh

else

rm -f initialization-zh-sh
wget --show-progress --quiet https://gh-proxy.org/https://raw.githubusercontent.com/ocnedkf/GQE-emulator/refs/heads/v0.2-beta/zh_CN/initialization-zh-sh
chmod +x initialization-zh-sh
./initialization-zh-sh
rm -f initialization-zh-sh

fi

fi

if [ ! -d "$HOME/storage" ]; then
echo -e "找不到外部存储！检查你的存储权限"
exit 1
fi

if ps a | grep -q '[w]ine'; then
env WINEPREFIX=$HOME/.gqe-data-v0.2 grun /data/data/com.termux/files/usr/glibc/bin/box64 /data/data/com.termux/files/usr/glibc/bin/wine /data/data/com.termux/files/usr/glibc/bin/wineboot -k >/dev/null 2>&1
fi

pkill -f virgl
virgl_test_server --use-gles --use-egl-surfaceless &

rm -rf $PREFIX/tmp/pulse-*
pulseaudio -k >/dev/null 2>&1
pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 >/dev/null 2>&1

pkill -f termux-x11
termux-x11 :13 >/dev/null 2>&1 &

if am start -n com.termux.x11/.MainActivity; then
sleep 0.8
termux-x11-preference displayResolutionMode:exact displayResolutionExact:1024x768 || echo "更改分辨率失败，可能需要自行设置"
else
echo "自动跳转Termux-x11失败，需确保已安装"
fi

env DXVK_ASYNC=1 BOX64_ASYNC=1 MESA_VK_DEVICE_SELECT=$(cat /data/data/com.termux/files/home/storage/shared/.gqe-start/mesa_var_v.txt) VK_ICD_FILENAMES=$(cat /data/data/com.termux/files/home/storage/shared/.gqe-start/mesa_var_f.txt) GALLIUM_DRIVER=$(cat /data/data/com.termux/files/home/storage/shared/.gqe-start/mesa_var.txt) WINEPREFIX=$HOME/.gqe-data-v0.2 LOCPATH=$HOME/.locale PULSE_SERVER=127.0.0.1 DXVK_HUD=1 MESA_NO_ERROR=1 LC_ALL=zh_CN.UTF-8 DISPLAY=:13 grun /data/data/com.termux/files/usr/glibc/bin/box64 /data/data/com.termux/files/usr/glibc/bin/wine explorer /desktop=shell,1024x768 Z:\\home\\storage\\shared\\.gqe-start\\start-gqe-v0.2.bat >/dev/null 2>&1

pkill -f termux-x11
pkill -f virgl
pulseaudio -k >/dev/null 2>&1
rm -rf $PREFIX/tmp/pulse-*
