#!/data/data/com.termux/files/usr/bin/bash
clear
echo -e "卸载脚本将在 15 秒后执行，执行后将彻底删除 GQE 及其数据\n"
echo -e "如要取消，请立即按 Ctrl+C 终止\n"
sleep 1

echo -e "\033[31m15\033[0m"
sleep 1
echo -e "\033[31m14\033[0m"
sleep 1
echo -e "\033[31m13\033[0m"
sleep 1
echo -e "\033[31m12\033[0m"
sleep 1
echo -e "\033[31m11\033[0m"
sleep 1
echo -e "\033[31m10\033[0m"
sleep 1
echo -e "\033[31m9\033[0m"
sleep 1
echo -e "\033[31m8\033[0m"
sleep 1
echo -e "\033[31m7\033[0m"
sleep 1
echo -e "\033[31m6\033[0m"
sleep 1
echo -e "\033[31m5\033[0m"
sleep 1
echo -e "\033[31m4\033[0m"
sleep 1
echo -e "\033[31m3\033[0m"
sleep 1
echo -e "\033[31m2\033[0m"
sleep 1
echo -e "\033[31m1\033[0m"
sleep 2
clear
echo -e "开始卸载 GQE..."

export PREFIX="/data/data/com.termux/files/usr"
export HOME="$PREFIX/../home"
export GQE_DATA=$HOME/.gqe-data-v0.3

rm -rf $PREFIX/bin/{start-gqe,kill-gqe}

rm -rf $GQE_DATA

rm -rf $HOME/storage/shared/.gqe-start

rm -rf $PREFIX/glibc/share/wine

clear

echo -e "卸载已完成；为保持环境完整性，下列依赖未被移除"
echo -e "请根据需要自行决定并使用 apt 手动卸载它们\n"

echo "pulseaudio termux-x11-nightly glibc-runner freetype-glibc libpulse-glibc libx11-glibc libxcb-glibc libxext-glibc libxft-glibc libdrm-glibc libffi-glibc libicu-glibc libpciaccess-glibc libxml2-glibc libxshmfence-glibc libxi-glibc libxrandr-glibc vulkan-icd-loader-glibc tar xz-utils wget libepoxy-glibc libxkbcommon-glibc libxcursor-glibc libxcomposite-glibc libxinerama-glibc libmount-glibc libthai-glibc libgraphite-glibc libpixman-glibc libjpeg-turbo-glibc x11-repo glibc-repo"

rm -rf "$0"
